// Generated by bpmn-to-code
@file:Suppress("unused")

package de.emaarco.example.adapter.process

import io.miragon.bpmn.runtime.BpmnEngine
import io.miragon.bpmn.runtime.BpmnFlow
import io.miragon.bpmn.runtime.BpmnRelations
import io.miragon.bpmn.runtime.BpmnTimer
import io.miragon.bpmn.runtime.ElementId
import io.miragon.bpmn.runtime.ProcessId
import kotlin.String
import kotlin.Suppress

object BikeOrderProcessProcessApi {
  val PROCESS_ID: ProcessId = ProcessId("bikeOrderProcess")

  val PROCESS_ENGINE: BpmnEngine = BpmnEngine.CAMUNDA_7

  /**
   * BPMN element ids as declared in the source model.
   * Typically used in process-level tests or when searching for tasks.
   * Worker runtime code rarely needs these.
   */
  object Elements {
    val BOUNDARY_EVENT_REMINDER: ElementId = ElementId("BoundaryEvent_reminder")

    val END_EVENT_REMINDER_SENT: ElementId = ElementId("EndEvent_reminderSent")

    val END_EVENT_SHIPPED: ElementId = ElementId("EndEvent_shipped")

    val GATEWAY_APPROVAL_MERGE: ElementId = ElementId("Gateway_approvalMerge")

    val GATEWAY_ORDER_VALUE: ElementId = ElementId("Gateway_orderValue")

    val START_EVENT_ORDER_RECEIVED: ElementId = ElementId("StartEvent_orderReceived")

    val TASK_AUTO_APPROVE: ElementId = ElementId("Task_AutoApprove")

    val TASK_CHARGE_PAYMENT: ElementId = ElementId("Task_ChargePayment")

    val TASK_MANAGER_APPROVAL: ElementId = ElementId("Task_ManagerApproval")

    val TASK_PREPARE_BIKE: ElementId = ElementId("Task_PrepareBike")

    val TASK_SEND_REMINDER: ElementId = ElementId("Task_SendReminder")

    val TASK_SHIP_ORDER: ElementId = ElementId("Task_ShipOrder")
  }

  /**
   * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
   * Kept as `const val String` because annotation arguments must be compile-time constants.
   */
  object ServiceTasks {
    const val BIKE_LEASING_AUTO_APPROVE: String = "bikeLeasing.autoApprove"

    const val BIKE_LEASING_CHARGE_PAYMENT: String = "bikeLeasing.chargePayment"

    const val BIKE_LEASING_SEND_REMINDER: String = "bikeLeasing.sendReminder"

    const val BIKE_LEASING_SHIP_ORDER: String = "bikeLeasing.shipOrder"
  }

  object Timers {
    val BOUNDARY_EVENT_REMINDER: BpmnTimer = BpmnTimer("Duration", "PT2M")
  }

  /**
   * Sequence flows between BPMN elements.
   * Mainly useful for process-model tooling, tests, and AI-agent consumers reasoning about the process shape.
   * Worker code typically does not need these.
   */
  object Flows {
    val FLOW_AUTO_TO_MERGE: BpmnFlow = BpmnFlow(
          id = "Flow_auto_to_merge",
          sourceRef = "Task_AutoApprove",
          targetRef = "Gateway_approvalMerge",
        )

    val FLOW_CHARGE_TO_SHIP: BpmnFlow = BpmnFlow(
          id = "Flow_charge_to_ship",
          sourceRef = "Task_ChargePayment",
          targetRef = "Task_ShipOrder",
        )

    val FLOW_MANAGER_TO_MERGE: BpmnFlow = BpmnFlow(
          id = "Flow_manager_to_merge",
          sourceRef = "Task_ManagerApproval",
          targetRef = "Gateway_approvalMerge",
        )

    val FLOW_MERGE_TO_PREPARE: BpmnFlow = BpmnFlow(
          id = "Flow_merge_to_prepare",
          sourceRef = "Gateway_approvalMerge",
          targetRef = "Task_PrepareBike",
        )

    val FLOW_PREPARE_TO_CHARGE: BpmnFlow = BpmnFlow(
          id = "Flow_prepare_to_charge",
          sourceRef = "Task_PrepareBike",
          targetRef = "Task_ChargePayment",
        )

    val FLOW_REMINDER_TO_SEND: BpmnFlow = BpmnFlow(
          id = "Flow_reminder_to_send",
          sourceRef = "BoundaryEvent_reminder",
          targetRef = "Task_SendReminder",
        )

    val FLOW_SEND_TO_REMINDER_END: BpmnFlow = BpmnFlow(
          id = "Flow_send_to_reminderEnd",
          sourceRef = "Task_SendReminder",
          targetRef = "EndEvent_reminderSent",
        )

    val FLOW_SHIP_TO_END: BpmnFlow = BpmnFlow(
          id = "Flow_ship_to_end",
          sourceRef = "Task_ShipOrder",
          targetRef = "EndEvent_shipped",
        )

    val FLOW_START_TO_VALUE: BpmnFlow = BpmnFlow(
          id = "Flow_start_to_value",
          sourceRef = "StartEvent_orderReceived",
          targetRef = "Gateway_orderValue",
        )

    val FLOW_VALUE_TO_AUTO: BpmnFlow = BpmnFlow(
          id = "Flow_value_to_auto",
          name = "< 1000",
          sourceRef = "Gateway_orderValue",
          targetRef = "Task_AutoApprove",
          isDefault = true,
        )

    val FLOW_VALUE_TO_MANAGER: BpmnFlow = BpmnFlow(
          id = "Flow_value_to_manager",
          name = "≥ 1000",
          sourceRef = "Gateway_orderValue",
          targetRef = "Task_ManagerApproval",
          condition = $$"""${orderTotal >= 1000}""",
        )
  }

  /**
   * Per-element graph metadata (previousElements / followingElements / parentId / boundary attachments).
   * Intended for tooling and tests, not worker runtime code.
   */
  object Relations {
    val BOUNDARY_EVENT_REMINDER: BpmnRelations = BpmnRelations(
          name = "After 2 minutes",
          previousElements = emptyList(),
          followingElements = listOf("Task_SendReminder"),
          parentId = null,
          attachedToRef = "Task_ManagerApproval",
          attachedElements = emptyList(),
        )

    val END_EVENT_REMINDER_SENT: BpmnRelations = BpmnRelations(
          name = "Reminder sent",
          previousElements = listOf("Task_SendReminder"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val END_EVENT_SHIPPED: BpmnRelations = BpmnRelations(
          name = "Order shipped",
          previousElements = listOf("Task_ShipOrder"),
          followingElements = emptyList(),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_APPROVAL_MERGE: BpmnRelations = BpmnRelations(
          previousElements = listOf("Task_ManagerApproval", "Task_AutoApprove"),
          followingElements = listOf("Task_PrepareBike"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val GATEWAY_ORDER_VALUE: BpmnRelations = BpmnRelations(
          name = "Order value?",
          previousElements = listOf("StartEvent_orderReceived"),
          followingElements = listOf("Task_ManagerApproval", "Task_AutoApprove"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val START_EVENT_ORDER_RECEIVED: BpmnRelations = BpmnRelations(
          name = "Order received",
          previousElements = emptyList(),
          followingElements = listOf("Gateway_orderValue"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val TASK_AUTO_APPROVE: BpmnRelations = BpmnRelations(
          name = "Auto-Approve",
          previousElements = listOf("Gateway_orderValue"),
          followingElements = listOf("Gateway_approvalMerge"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val TASK_CHARGE_PAYMENT: BpmnRelations = BpmnRelations(
          name = "Charge Payment",
          previousElements = listOf("Task_PrepareBike"),
          followingElements = listOf("Task_ShipOrder"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val TASK_MANAGER_APPROVAL: BpmnRelations = BpmnRelations(
          name = "Manager Approval",
          previousElements = listOf("Gateway_orderValue"),
          followingElements = listOf("Gateway_approvalMerge"),
          parentId = null,
          attachedToRef = null,
          attachedElements = listOf("BoundaryEvent_reminder"),
        )

    val TASK_PREPARE_BIKE: BpmnRelations = BpmnRelations(
          name = "Prepare Bike",
          previousElements = listOf("Gateway_approvalMerge"),
          followingElements = listOf("Task_ChargePayment"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val TASK_SEND_REMINDER: BpmnRelations = BpmnRelations(
          name = "Send Reminder",
          previousElements = listOf("BoundaryEvent_reminder"),
          followingElements = listOf("EndEvent_reminderSent"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )

    val TASK_SHIP_ORDER: BpmnRelations = BpmnRelations(
          name = "Ship Order",
          previousElements = listOf("Task_ChargePayment"),
          followingElements = listOf("EndEvent_shipped"),
          parentId = null,
          attachedToRef = null,
          attachedElements = emptyList(),
        )
  }
}
