// Generated by bpmn-to-code
@file:Suppress("unused")

package de.emaarco.example.adapter.process

import kotlin.String
import kotlin.Suppress

object NewsletterSubscriptionProcessApi {
  const val PROCESS_ID: String = "newsletterSubscription"

  object Elements {
    const val TIMER_EVERY_DAY: String = "Timer_EveryDay"

    const val ERROR_EVENT_INVALID_MAIL: String = "ErrorEvent_InvalidMail"

    const val TIMER_AFTER_3_DAYS: String = "Timer_After3Days"

    const val ACTIVITY_CONFIRM_REGISTRATION: String = "Activity_ConfirmRegistration"

    const val SUB_PROCESS_CONFIRMATION: String = "SubProcess_Confirmation"

    const val END_EVENT_SUBSCRIPTION_CONFIRMED: String = "EndEvent_SubscriptionConfirmed"

    const val END_EVENT_REGISTRATION_ABORTED: String = "EndEvent_RegistrationAborted"

    const val END_EVENT_REGISTRATION_NOT_POSSIBLE: String =
        "EndEvent_RegistrationNotPossible"

    const val END_EVENT_REGISTRATION_COMPLETED: String = "EndEvent_RegistrationCompleted"

    const val ACTIVITY_SEND_CONFIRMATION_MAIL: String = "Activity_SendConfirmationMail"

    const val ACTIVITY_ABORT_REGISTRATION: String = "Activity_AbortRegistration"

    const val ACTIVITY_SEND_WELCOME_MAIL: String = "Activity_SendWelcomeMail"

    const val START_EVENT_SUBMIT_REGISTRATION_FORM: String =
        "StartEvent_SubmitRegistrationForm"

    const val START_EVENT_REQUEST_RECEIVED: String = "StartEvent_RequestReceived"
  }

  object Messages {
    const val MESSAGE_FORM_SUBMITTED: String = "Message_FormSubmitted"

    const val MESSAGE_SUBSCRIPTION_CONFIRMED: String = "Message_SubscriptionConfirmed"
  }

  object TaskTypes {
    const val ACTIVITY_SEND_CONFIRMATION_MAIL: String = "#{sendConfirmationMailDelegate}"

    const val ACTIVITY_ABORT_REGISTRATION: String = "#{abortRegistrationDelegate}"

    const val ACTIVITY_SEND_WELCOME_MAIL: String = "#{sendWelcomeMailDelegate}"
  }

  object Timers {
    val TIMER_EVERY_DAY: BpmnTimer = BpmnTimer("Duration", "PT1M")

    val TIMER_AFTER_3_DAYS: BpmnTimer = BpmnTimer("Duration", "PT2M30S")

    data class BpmnTimer(
      val type: String,
      val timerValue: String,
    )
  }

  object Errors {
    val ERROR_INVALID_MAIL: BpmnError = BpmnError("Error_InvalidMail", "500")

    data class BpmnError(
      val name: String,
      val code: String,
    )
  }

  object Signals {
    const val SIGNAL_REGISTRATION_NOT_POSSIBLE: String = "Signal_RegistrationNotPossible"
  }
}
